
###########
# Font    #
###########
# font_family      family="JetBrainsMonoNL Nerd Font Mono"
# bold_font        auto
# italic_font      auto
# bold_italic_font auto

################
# Transparency #
################

background_opacity 0.16

################
# Base colors  #
################

foreground #ffffff
cursor     #bbbbbb

# Normal 
color0  #020202
color1  #ce1818
coler2  #259b0d
color3  #e0dd1d
color4  #424ffd
color5  #9101bd
color6  #59c7e2
color7  #cccccc

# Bright
color8  #2b2a2a
color9  #E65A5A
color10 #66D663
color11 #F2FA84
color12 #6C97F0
color13 #F734CA
color14 #89EBFA
color15 #ffffff

#################
# Selection/UI  #
#################

cursor_shape block
cursor_blink_interval 0.55

selection_foreground #616159
selection_background #ffdddd


####################
# Scrollback/text  #
####################

scrollback_lines 10000
force_ltr yes

####################
# Borders/window   #
####################

window_border_width 2
active_border_color   #ebebeb
inactive_border_color #4d4d4d

####################
# keybindings      #
####################



# map ctrl+c copy_to_clipboard
# map ctrl+v paste_from_clipboard
map ctrl+shift+a new_window
map ctrl+shift+s close_window  

#####################
# other Settings    #
#####################

confirm_os_window_close 0


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMonoNL Nerd Font Mono' postscript_name=JetBrainsMonoNLNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS